import { injectScoreBadge } from "../src/components/score-badge";

// The wasm-pack JS module is bundled by Vite.  The binary (.wasm) is a
// separate static asset copied to public/ and fetched via runtime URL.
// @ts-ignore — generated by wasm-pack; types live in src/wasm/provenir_core.d.ts
import init, { score_content } from "../src/wasm/provenir_core.js";

import type { ScoreOutput } from "../src/types";

let wasmInitialised = false;

async function ensureWasm(): Promise<void> {
  if (!wasmInitialised) {
    // In a content script, fetch() runs in the page's security context, so
    // the .wasm binary must be declared in web_accessible_resources and
    // referenced via chrome.runtime.getURL().  Newer wasm-pack output also
    // requires the options-object form of init rather than a bare URL.
    await init({ module_or_path: chrome.runtime.getURL("provenir_core_bg.wasm") });
    wasmInitialised = true;
  }
}

function extractArticleText(): string {
  const root =
    document.querySelector("article") ??
    document.querySelector("main") ??
    document.body;

  if (!root) return "";

  const clone = root.cloneNode(true) as HTMLElement;
  clone.querySelectorAll("script, style, noscript, nav, footer, header").forEach(
    (el) => el.remove(),
  );

  const raw = clone.innerText ?? clone.textContent ?? "";
  return raw.replace(/\s+/g, " ").trim();
}

function extractC2paMeta(): string | null {
  const meta = document.querySelector<HTMLMetaElement>(
    'meta[name="c2pa:manifest"], meta[property="c2pa:manifest"]',
  );
  return meta?.content ?? null;
}

function injectBadge(score: number): void {
  injectScoreBadge(score);
}

export default defineContentScript({
  matches: ["*://*/*"],
  async main() {
    await ensureWasm();

    const text = extractArticleText();
    if (text.length < 200) return;

    const c2pa_manifest = extractC2paMeta();

    let wasmOutput: ScoreOutput;
    try {
      wasmOutput = score_content({ text, url: location.href, c2pa_manifest }) as ScoreOutput;
    } catch (err) {
      console.error("[Provenir] WASM scoring failed:", err);
      return;
    }

    chrome.runtime.sendMessage(
      {
        type: "PROVENIR_SCORE_REQUEST",
        payload: { ...wasmOutput, text },
      },
      (response: { score: number; breakdown: Record<string, unknown> } | null) => {
        if (chrome.runtime.lastError || response === null) {
          console.error("[Provenir] Background response error:", chrome.runtime.lastError);
          return;
        }
        injectBadge(response.score);
      },
    );
  },
});
